from enum import Enum


class ScopeType(str, Enum):
    GLOBAL = "GLOBAL"
    SERVICE = "SERVICE"


class ServiceType(str, Enum):
    MICROSERVICE = "MICROSERVICE"
    MONOLITH = "MONOLITH"
    OTHER = "OTHER"


class RequestType(str, Enum):
    EDIT_NODE = "EDIT_NODE"
    CREATE_SUBCONFIG = "CREATE_SUBCONFIG"
    ROLLBACK = "ROLLBACK"


class ChangeRequestStatus(str, Enum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    IN_REVIEW = "IN_REVIEW"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CONFLICTED = "CONFLICTED"
    IMPLEMENTING = "IMPLEMENTING"
    IMPLEMENTED = "IMPLEMENTED"
    FAILED = "FAILED"


class ReviewDecision(str, Enum):
    COMMENT = "COMMENT"
    REQUEST_CHANGES = "REQUEST_CHANGES"
    APPROVE = "APPROVE"
    REJECT = "REJECT"


class JobType(str, Enum):
    IMPLEMENT = "IMPLEMENT"
    ROLLBACK = "ROLLBACK"


class JobStatus(str, Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class VersionStatus(str, Enum):
    PENDING = "PENDING"
    ACTIVE = "ACTIVE"
    SUPERSEDED = "SUPERSEDED"
    FAILED = "FAILED"
    ROLLED_BACK = "ROLLED_BACK"


class RollbackStatus(str, Enum):
    REQUESTED = "REQUESTED"
    APPROVED = "APPROVED"
    IMPLEMENTING = "IMPLEMENTING"
    ROLLED_BACK = "ROLLED_BACK"
    FAILED = "FAILED"


class SyncStatus(str, Enum):
    PENDING = "PENDING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"


class RoleName(str, Enum):
    CONFIG_AUTHOR = "CONFIG_AUTHOR"
    CONFIG_REVIEWER = "CONFIG_REVIEWER"
    CONFIG_IMPLEMENTER = "CONFIG_IMPLEMENTER"
    CONFIG_ADMIN = "CONFIG_ADMIN"
    CONFIG_AUDITOR = "CONFIG_AUDITOR"


ACTIVE_VERSION = "ACTIVE_VERSION"
PROPOSED_REVISION = "PROPOSED_REVISION"
CANDIDATE_VERSION = "CANDIDATE_VERSION"


MAX_NODES_DEFAULT = 100
MAX_DEPTH_DEFAULT = 20
MAX_KEYS_DEFAULT = 1000
MAX_VALUE_SIZE_DEFAULT = 10000

