services:
  payment-svc:
    build:
      context: ../..
      dockerfile: examples/payment-svc/Dockerfile
    image: configsphere-payment-svc
    container_name: configsphere_payment_svc
    ports:
      - "5050:5001"
    environment:
      CONFIGSPHERE_URL: "http://web:8000/api/v1"
    networks:
      - backend_default

networks:
  backend_default:
    external: true
