# Generated by Django 4.2.29 on 2026-03-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('schema_created', 'schema_created'), ('config_item_created', 'config_item_created'), ('config_version_created', 'config_version_created'), ('validation_passed', 'validation_passed'), ('validation_failed', 'validation_failed'), ('version_activated', 'version_activated'), ('version_archived', 'version_archived'), ('resolved_config_fetched', 'resolved_config_fetched')], db_index=True, max_length=64)),
                ('actor', models.CharField(blank=True, max_length=255, null=True)),
                ('config_item_id_ref', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('config_version_id_ref', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('schema_id_ref', models.BigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='audits_audi_event_t_7a66b2_idx')],
            },
        ),
    ]
