# Generated by Django 4.2.29 on 2026-03-22 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('scope_level', models.CharField(choices=[('global', 'Global'), ('region', 'Region'), ('group', 'Group'), ('service', 'Service')], db_index=True, max_length=32)),
                ('global_name', models.CharField(default='default', max_length=255)),
                ('region_name', models.CharField(blank=True, max_length=255, null=True)),
                ('group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('service_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('payload', models.JSONField()),
                ('checksum', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='draft', max_length=32)),
                ('validation_error', models.TextField(blank=True, default='')),
                ('change_summary', models.TextField(blank=True, default='')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='configs.configitem')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='configitem',
            name='active_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_item', to='configs.configversion'),
        ),
        migrations.AddField(
            model_name='configitem',
            name='schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='config_items', to='schemas.schemadefinition'),
        ),
        migrations.AddIndex(
            model_name='configversion',
            index=models.Index(fields=['config_item', 'status'], name='configs_con_config__35884c_idx'),
        ),
        migrations.AddConstraint(
            model_name='configversion',
            constraint=models.UniqueConstraint(fields=('config_item', 'version_number'), name='uq_config_version_number'),
        ),
        migrations.AddIndex(
            model_name='configitem',
            index=models.Index(fields=['scope_level', 'service_name'], name='configs_con_scope_l_e6728d_idx'),
        ),
        migrations.AddIndex(
            model_name='configitem',
            index=models.Index(fields=['scope_level', 'region_name'], name='configs_con_scope_l_c58184_idx'),
        ),
        migrations.AddConstraint(
            model_name='configitem',
            constraint=models.UniqueConstraint(fields=('key', 'scope_level', 'global_name', 'region_name', 'group_name', 'service_name'), name='uq_config_item_scope_key'),
        ),
    ]
