# Generated by Django 4.2.29 on 2026-03-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configitem',
            name='group_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='configitem',
            name='region_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='configitem',
            name='service_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
